"""empty message

Revision ID: 072781e86ce8
Revises: 3c29fa634301
Create Date: 2023-01-25 12:50:28.142498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '072781e86ce8'
down_revision = '3c29fa634301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_title', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10000),
               comment='标题',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_title', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10000),
               comment=None,
               existing_comment='标题',
               existing_nullable=True)
    # ### end Alembic commands ###
