"""empty message

Revision ID: 096c3283e347
Revises: 1f0dbfa12852
Create Date: 2023-01-18 12:49:42.057305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096c3283e347'
down_revision = '1f0dbfa12852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_user', sa.Column('handicap_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'admin_user', 'admin_handicap', ['handicap_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_user', type_='foreignkey')
    op.drop_column('admin_user', 'handicap_id')
    # ### end Alembic commands ###
