"""empty message

Revision ID: 13cddf53b49c
Revises: 40efd45b5204
Create Date: 2023-02-03 15:11:44.347456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13cddf53b49c'
down_revision = '40efd45b5204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_domain_https',
    sa.Column('id', sa.Integer(), nullable=False, comment='域名ID'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='域名名称'),
    sa.Column('expir_day', sa.Integer(), nullable=True, comment='到期时间'),
    sa.Column('is_ssl', sa.Integer(), nullable=True, comment='是否检测'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='添加时间'),
    sa.Column('update_at', sa.DateTime(), nullable=True, comment='修改时间'),
    sa.Column('handicap_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['handicap_id'], ['admin_handicap.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_admin_domain_https_expir_day'), 'admin_domain_https', ['expir_day'], unique=False)
    op.create_index(op.f('ix_admin_domain_https_name'), 'admin_domain_https', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_domain_https_name'), table_name='admin_domain_https')
    op.drop_index(op.f('ix_admin_domain_https_expir_day'), table_name='admin_domain_https')
    op.drop_table('admin_domain_https')
    # ### end Alembic commands ###
