"""empty message

Revision ID: 168da286d021
Revises: 2c33cd23f31d
Create Date: 2023-01-13 15:39:07.729028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168da286d021'
down_revision = '2c33cd23f31d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admin_member_tag_ibfk_1', 'admin_member_tag', type_='foreignkey')
    op.drop_constraint('admin_member_tag_ibfk_2', 'admin_member_tag', type_='foreignkey')
    op.create_foreign_key(None, 'admin_member_tag', 'admin_tag', ['tag_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'admin_member_tag', 'admin_member', ['member_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_member_tag', type_='foreignkey')
    op.drop_constraint(None, 'admin_member_tag', type_='foreignkey')
    op.create_foreign_key('admin_member_tag_ibfk_2', 'admin_member_tag', 'admin_tag', ['tag_id'], ['id'])
    op.create_foreign_key('admin_member_tag_ibfk_1', 'admin_member_tag', 'admin_member', ['member_id'], ['id'])
    # ### end Alembic commands ###
