"""empty message

Revision ID: 25e4333b1a4b
Revises: 13cddf53b49c
Create Date: 2023-02-03 15:48:44.085838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25e4333b1a4b'
down_revision = '13cddf53b49c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_domain_https', sa.Column('enable', sa.Integer(), nullable=True, comment='是否检测'))
    op.drop_column('admin_domain_https', 'is_ssl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_domain_https', sa.Column('is_ssl', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='是否检测'))
    op.drop_column('admin_domain_https', 'enable')
    # ### end Alembic commands ###
