"""empty message

Revision ID: 2c33cd23f31d
Revises: e073cd7d2027
Create Date: 2023-01-12 15:08:06.638164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c33cd23f31d'
down_revision = 'e073cd7d2027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_tag', sa.Column('color', sa.String(length=255), nullable=True, comment='标签颜色'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_tag', 'color')
    # ### end Alembic commands ###
