"""empty message

Revision ID: 4a5006366110
Revises: 7bc109aac8c8
Create Date: 2023-01-10 13:13:31.644226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a5006366110'
down_revision = '7bc109aac8c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_tag',
    sa.Column('id', sa.Integer(), nullable=False, comment='标签ID'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='标签名称'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_member_tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='标识'),
    sa.Column('member_id', sa.Integer(), nullable=True, comment='会员编号'),
    sa.Column('tag_id', sa.Integer(), nullable=True, comment='标签编号'),
    sa.ForeignKeyConstraint(['member_id'], ['admin_member.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['admin_tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('admin_member', 'tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_member', sa.Column('tag', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='彩金标签'))
    op.drop_table('admin_member_tag')
    op.drop_table('admin_tag')
    # ### end Alembic commands ###
