"""empty message

Revision ID: 7ee1e614c259
Revises: 072781e86ce8
Create Date: 2023-01-26 20:07:05.836209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee1e614c259'
down_revision = '072781e86ce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_title', sa.Column('weight', sa.Integer(), nullable=True, comment='权重'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_title', 'weight')
    # ### end Alembic commands ###
