"""empty message

Revision ID: 98e5bcc03405
Revises: 25e4333b1a4b
Create Date: 2023-02-06 11:44:17.456170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e5bcc03405'
down_revision = '25e4333b1a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_admin_title_status'), 'admin_title', ['status'], unique=False)
    op.create_index(op.f('ix_admin_title_tag'), 'admin_title', ['tag'], unique=False)
    op.create_index(op.f('ix_admin_title_upload_tag'), 'admin_title', ['upload_tag'], unique=False)
    op.create_index(op.f('ix_admin_title_url'), 'admin_title', ['url'], unique=False)
    op.create_index(op.f('ix_admin_title_weight'), 'admin_title', ['weight'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_title_weight'), table_name='admin_title')
    op.drop_index(op.f('ix_admin_title_url'), table_name='admin_title')
    op.drop_index(op.f('ix_admin_title_upload_tag'), table_name='admin_title')
    op.drop_index(op.f('ix_admin_title_tag'), table_name='admin_title')
    op.drop_index(op.f('ix_admin_title_status'), table_name='admin_title')
    # ### end Alembic commands ###
