"""empty message

Revision ID: b752ce55cd13
Revises: 7e2c9a4a1927
Create Date: 2023-01-18 19:35:54.734820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b752ce55cd13'
down_revision = '7e2c9a4a1927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_admin_member_tag_member_id'), 'admin_member_tag', ['member_id'], unique=False)
    op.create_index(op.f('ix_admin_member_tag_tag_id'), 'admin_member_tag', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_member_tag_tag_id'), table_name='admin_member_tag')
    op.drop_index(op.f('ix_admin_member_tag_member_id'), table_name='admin_member_tag')
    # ### end Alembic commands ###
