"""empty message

Revision ID: c4c27337e327
Revises: 168da286d021
Create Date: 2023-01-14 19:57:52.746516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c27337e327'
down_revision = '168da286d021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admin_handicap', ['name'])
    op.create_unique_constraint(None, 'admin_handicap', ['id'])
    op.create_unique_constraint(None, 'admin_tag', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_tag', type_='unique')
    op.drop_constraint(None, 'admin_handicap', type_='unique')
    op.drop_constraint(None, 'admin_handicap', type_='unique')
    # ### end Alembic commands ###
