"""empty message

Revision ID: cf25d0d22ad5
Revises: e0b728227720
Create Date: 2023-01-18 16:11:35.339743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf25d0d22ad5'
down_revision = 'e0b728227720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_tag', sa.Column('handicap_id', sa.Integer(), nullable=True))
    op.drop_index('name', table_name='admin_tag')
    op.create_foreign_key(None, 'admin_tag', 'admin_handicap', ['handicap_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_tag', type_='foreignkey')
    op.create_index('name', 'admin_tag', ['name'], unique=False)
    op.drop_column('admin_tag', 'handicap_id')
    # ### end Alembic commands ###
