"""empty message

Revision ID: e073cd7d2027
Revises: 4a5006366110
Create Date: 2023-01-10 13:34:39.506359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e073cd7d2027'
down_revision = '4a5006366110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_handicap', sa.Column('update_at', sa.DateTime(), nullable=True, comment='更新时间'))
    op.add_column('admin_member', sa.Column('delete_at', sa.DateTime(), nullable=True, comment='删除时间'))
    op.add_column('admin_tag', sa.Column('create_at', sa.DateTime(), nullable=True, comment='添加时间'))
    op.add_column('admin_tag', sa.Column('update_at', sa.DateTime(), nullable=True, comment='修改时间'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_tag', 'update_at')
    op.drop_column('admin_tag', 'create_at')
    op.drop_column('admin_member', 'delete_at')
    op.drop_column('admin_handicap', 'update_at')
    # ### end Alembic commands ###
