"""empty message

Revision ID: e0b728227720
Revises: 096c3283e347
Create Date: 2023-01-18 14:27:38.787174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b728227720'
down_revision = '096c3283e347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_user', sa.Column('is_super', sa.Integer(), nullable=True, comment='是否超级管理员'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_user', 'is_super')
    # ### end Alembic commands ###
